# Generated by Django 5.0.3 on 2025-03-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=10, unique=True)),
                ('event_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('level', models.CharField(max_length=50)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event_code', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('seats_left', models.PositiveIntegerField()),
            ],
        ),
    ]
