# Generated by Django 5.0.3 on 2025-03-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='event_code',
        ),
    ]
