# Generated by Django 5.0.3 on 2025-03-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_assessment_event_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='event_code',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
