# Generated by Django 5.0.3 on 2025-03-04 05:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_assessment_event_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='faculty',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='event_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
