# Generated by Django 5.0.3 on 2025-04-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_assessment_faculty_alter_assessment_event_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='faculty',
            field=models.CharField(default='Unknown Faculty', max_length=255),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='event_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='faculty',
            field=models.CharField(default='Unknown Faculty', max_length=255),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
